using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Windows.Forms;

namespace DoAnCNPM
{
    public partial class frm_TimKiemKhachHang : DevExpress.XtraEditors.XtraForm
    {
        public frm_TimKiemKhachHang()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            gcTimKiem.DataSource = new DAL_BLL.QLBanDoGoDataContext().KHACHHANGs;
        }
    }
}
