using DAL_BLL;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Windows.Forms;

namespace DoAnCNPM
{
    public partial class frm_KhachHang : DevExpress.XtraEditors.XtraForm
    {
        KhachHang_BLL kh = new KhachHang_BLL();
        int flat = 0;
        public frm_KhachHang()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            LoadBang();
        }

        private void LoadBang()
        {
            gcTimKiem.DataSource = kh.LoadKhachHang();
        }
        private void btnLuu_Click(object sender, EventArgs e)
        {
            if (flat == 1)
            {
                ThemHD();
            }
            else if (flat == 2)
            {
                SuaHD();
            }
            SetReadOnly(false);
        }



        private void btnThem_Click(object sender, EventArgs e)
        {
            SetReadOnly(true);
            txtMaKH.Text = "";
            txtTenKH.Text = "";
            txtDiaChi.Text = "";
            txtSDT.Text = "";
            txtEmail.Text = "";
            flat = 1;
        }

        private void SetReadOnly(bool t)
        {
            txtTenKH.ReadOnly = !t;
            txtDiaChi.ReadOnly = !t;
            txtSDT.ReadOnly = !t;
            txtEmail.ReadOnly = !t;
        }

        private void btnSua_Click(object sender, EventArgs e)
        {
            SetReadOnly(true);
            flat = 2;
        }

        private void txtSDT_KeyPress(object sender, KeyPressEventArgs e)
        {
            if(!Char.IsDigit(e.KeyChar) && !Char.IsControl(e.KeyChar))
            {
                e.Handled = true;
            }    
        }

        private void gcTimKiem_Click(object sender, EventArgs e)
        {
            
        }

        private void gvTimKiem_FocusedRowChanged(object sender, DevExpress.XtraGrid.Views.Base.FocusedRowChangedEventArgs e)
        {
            try
            {
                if (gvTimKiem.RowCount != 0)
                {
                    txtMaKH.Text = gvTimKiem.GetRowCellValue(gvTimKiem.FocusedRowHandle, "MAKHACHHANG").ToString();
                    txtTenKH.Text = gvTimKiem.GetRowCellValue(gvTimKiem.FocusedRowHandle, "TENKHACHHANG").ToString();
                    txtSDT.Text = gvTimKiem.GetRowCellValue(gvTimKiem.FocusedRowHandle, "DIENTHOAI").ToString();
                    txtEmail.Text = gvTimKiem.GetRowCellValue(gvTimKiem.FocusedRowHandle, "EMAIL").ToString();
                    txtDiaChi.Text = gvTimKiem.GetRowCellValue(gvTimKiem.FocusedRowHandle, "DIACHI").ToString();
                    
                }
            }
            catch
            {
            }
        }

        private void btnTimKiem_Click(object sender, EventArgs e)
        {
            gcTimKiem.DataSource = kh.LoadKHTheoTen(searchControl1.Text);
        }

        private void ThemHD()
        {
            int id = gvTimKiem.FocusedRowHandle;
            try
            {

                string tenkh = txtTenKH.Text;
                string diachi = txtDiaChi.Text;
                string sdt = txtSDT.Text;

                DialogResult result;
                result = MessageBox.Show("Bạn Có Muốn Thêm Thông tin khách hàng ?",
                    "Thông báo", MessageBoxButtons.YesNo, MessageBoxIcon.Question, MessageBoxDefaultButton.Button2);
                if (result == DialogResult.Yes)
                {

                    kh.ThemKH("KH", tenkh, diachi, sdt, txtEmail.Text);
                    LoadBang();
                    MessageBox.Show("Thêm Thành Công " + txtMaKH.Text, "Thông Báo");

                }
            }
            catch
            {
                MessageBox.Show("Có Vấn Đề Trong Việc thêm thông tin khách hàng ");
            }
        }


        private void SuaHD()
        {
            int id = gvTimKiem.FocusedRowHandle;
            try
            {

                string tenkh = txtTenKH.Text;
                string diachi = txtDiaChi.Text;
                string sdt = txtSDT.Text;

                DialogResult result;
                result = MessageBox.Show("Bạn Có Muốn Sửa Thông tin khách hàng ?",
                    "Thông báo", MessageBoxButtons.YesNo, MessageBoxIcon.Question, MessageBoxDefaultButton.Button2);
                if (result == DialogResult.Yes)
                {

                    kh.suaKH(txtMaKH.Text, tenkh, diachi, sdt, txtEmail.Text);
                    LoadBang();
                    MessageBox.Show("Sửa Thành Công " + txtMaKH.Text, "Thông Báo");

                }
            }
            catch
            {
                MessageBox.Show("Có Vấn Đề Trong Việc Sửa thông tin", "Thông Báo");
            }
        }


    }

}
